### ISSUE TITLE
/rss/ is partially broken

### ISSUE THREAD

**Issue by fuzzyroddis** [cure53/H5SC#8]
`https://html5sec.org/rss/` works but...
```
Not Found

The requested URL /rss/+ was not found on this server.
```
```
Not Found

The requested URL /rss/+1234/ was not found on this server.
```
```
Not Found

The requested URL /rss/1234/ was not found on this server.
```

`/rss/.htaccess` hasn't changed and I would have thought it was an `AllowOverride` problem but `https://html5sec.org/r/` works. hmmm.

**Comment by cure53** [comment]
We have been having problems with this feature for quite some time as the behaviors differ on Apache 2.4 compared to Apache 2.2 and other web-servers. 

I am actually tempted to simply remove the feature but am not sure if it is commonly used. Our logs say no but I do not know about external H5Sc instances. 

I am also happy to accept a pull request for a fix. Any thoughts?

**Comment by StevenRoddis** [comment]
I'll have a look at this, I actually wanted to use this feature the other week; I forget what for, I think I was testing some web based rss clients.

If I had to guess I'd say the `+` is being interpreted as a space.

**Comment by cure53** [comment]
Yeah, that might make sense. I have no time to look into this right now, if you have a fix I'd happily accept the PR :)

**Comment by StevenRoddis** [comment]
Cheers, I plan to have a look at this and if possible make a PR this week.

**Comment by cure53** [comment]
Thanks, appreciated :)

**Comment by cure53** [comment]
Closed for lack of activity
